#!/bin/sh
# Regenerate everything git-ignored: imports.json, the lifted PPU tree, the HLE
# NID table and the lifted SPURS jobs. Run from the repo root.
set -e
PS3RECOMP="${PS3RECOMP:-/g/recomp/ps3}"

# The executable sections are .init, .text (0x10230..0x250DA8), .fini and the
# .lib.stub import trampolines (0x250DCC..0x2525AC, 191 stubs). --code-end sits
# just past the stubs so --hle-stubs has something to rewrite, and no further:
# .rodata follows in the same R-X segment.
CODE_END=0x2525AC

python "$PS3RECOMP/tools/gen_imports.py" game/EBOOT.elf -o imports.json
python "$PS3RECOMP/tools/find_functions.py" game/EBOOT.elf --output analysis/functions.json

rm -rf src/recomp src/gen && mkdir -p src/recomp src/gen
python "$PS3RECOMP/tools/ppu_lifter.py" game/EBOOT.elf \
    --functions analysis/functions.json \
    --hle-stubs imports.json \
    --code-end "$CODE_END" \
    -o src/recomp

python "$PS3RECOMP/tools/gen_hle_nids.py" --all --out src/gen/ppu_hle_nids.cpp

# No embedded SPU ELF images (extract_spu_images.py finds none).
rm -rf src/spu_gen && mkdir -p src/spu_gen

# ---- SPURS job binaries -----------------------------------------------------
# Raw code+data blobs the title hands to its "crTaskRunJobList" job chain,
# loaded at LS 0 -- not ELFs, so the extractor cannot see them. Both live in the
# EBOOT's .data (file offset = vaddr - 0x10000), so they are cut out here rather
# than captured with SPU_DUMP_MISS; file names carry the runtime's fingerprint.
# Unlifted, each MISSes and completes empty: the front end's fragment programs
# are never written and every draw is dropped at PSO build (fp size zero).
mkdir -p spu_miss
dd if=game/EBOOT.elf of=spu_miss/spujob_96975E2984EFE57B_41856.bin bs=1 skip=$((0x281F80)) count=41856 2>/dev/null
dd if=game/EBOOT.elf of=spu_miss/spujob_84CC39BF3EF23DA3_816.bin   bs=1 skip=$((0x28C300)) count=816   2>/dev/null
OUT=src/spu_gen/spu_jobs.c
IMG=2
{
  echo "/* GENERATED by tools/relift.sh: the lifted SPURS job binaries. */"
  echo "#include \"spu_workload.h\""
  echo "extern void spu_begin_image(int image_id);"
} > "$OUT.tmp"
REG=""
for J in spu_miss/spujob_*.bin; do
    [ -f "$J" ] || continue
    FP=$(basename "$J" .bin | cut -d_ -f2)
    P="job_${FP}_"
    python "$PS3RECOMP/tools/find_spu_functions.py" "$J" --raw --base 0 \
        --out "spu_miss/job_${FP}_funcs.json"
    rm -rf "src/spu_gen/job_$FP" && mkdir -p "src/spu_gen/job_$FP"
    python "$PS3RECOMP/tools/spu_lifter.py" "$J" --base 0 \
        --functions "spu_miss/job_${FP}_funcs.json" \
        --symbol-prefix "$P" -o "src/spu_gen/job_$FP"
    echo "extern void ${P}spu_func_00000000(spu_context*); extern void ${P}spu_recomp_register(void);" >> "$OUT.tmp"
    REG="$REG    spu_begin_image($IMG); ${P}spu_recomp_register();
    spu_workload_register_img(0x${FP}ULL, ${P}spu_func_00000000, $IMG, \"job_$FP\");
"
    IMG=$((IMG + 1))
done
{
  echo "__attribute__((constructor)) static void midway_spu_jobs_register(void)"
  echo "{"
  printf "%s" "$REG"
  echo "    spu_begin_image(0);"
  echo "}"
} >> "$OUT.tmp"
mv "$OUT.tmp" "$OUT"
